name: Flutter CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      # - run: flutter format --set-exit-if-changed .
      # - run: flutter analyze .
      - run: flutter build apk --verbose --debug
      - uses: actions/upload-artifact@v3
        with:
          name: debug-apk
          path: build\app\outputs\flutter-apk\app-release.apk